[versions]
desugar_jdk_libs = "2.0.4"
media3 = "1.4.0" # 1.3.0: 19 java8  1.2.1: 17 media3-datasource-okhttp:1.2.1:21
nanohttpd = "2.3.1"
gua64 = "1.4.5"
recyclerview = "1.3.2"
zxing = "3.5.3"
glide = "4.16.0" # java7

gson = "2.10.1" # 19:2.10.1 #api17:2.9.1
okhttp = "3.12.13" #  19: 3.12.13
retrofit = "2.6.4" # 21:2.9.0 17:2.6.4

core_ktx = "1.13.1" #api17:1.12.0
lifecycle = "2.8.4"
constraintlayout = "2.1.4"
serialization = "1.6.3"
coroutines = "1.8.1"

android-gradle-plugin = "8.7.3"
kotlin-android = "2.0.0"
appcompat = "1.6.1" #api17+: 1.6.1

multidex = "2.0.1"

conscrypt = "2.5.2" #api17+

[libraries]
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-exoplayer-rtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-datasource-rtmp = { module = "androidx.media3:media3-datasource-rtmp", version.ref = "media3" }

nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
gua64 = { module = "io.github.lizongying:gua64", version.ref = "gua64" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

#api17+
conscrypt = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
